# Generated by Django 3.1.7 on 2021-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210517_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О парикмахерской', 'verbose_name_plural': 'О парикмахерской'},
        ),
        migrations.AddField(
            model_name='about',
            name='titleAbout',
            field=models.CharField(default=2, max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
