# Generated by Django 3.1.7 on 2021-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210519_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atmosfere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Добвить фото')),
                ('podpis', models.CharField(max_length=90, verbose_name='Придумай подпись к фото')),
            ],
            options={
                'verbose_name': 'Атмосфера',
                'verbose_name_plural': 'Атмосфера',
            },
        ),
    ]
