# Generated by Django 3.1.7 on 2021-05-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone_number',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес и телефон', 'verbose_name_plural': 'Адреса и телефоны'},
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default=2345, max_length=20, verbose_name='Введи номер телефона'),
            preserve_default=False,
        ),
    ]
