# Generated by Django 3.1.7 on 2021-05-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210524_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='titlePr',
        ),
    ]
