# Generated by Django 3.1.7 on 2021-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210525_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_for_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleAbout', models.CharField(default='Введи желаемое название заголовка', max_length=100, verbose_name='Заголовок')),
                ('titlePrice', models.CharField(default='Введи желаемое название заголовка', max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовки',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='titleAbout',
        ),
        migrations.RemoveField(
            model_name='services',
            name='titlePr',
        ),
    ]
