# Generated by Django 3.2.4 on 2021-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210525_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairdressers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairdresser', models.CharField(max_length=200, verbose_name='Фамилия и имя')),
                ('master', models.CharField(max_length=40, verbose_name='Уровень мастерства')),
                ('aboutMaster', models.CharField(max_length=255, verbose_name='Немного о мастере')),
                ('avatar', models.ImageField(upload_to='img/', verbose_name='Добавить фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Парихмахер',
                'verbose_name_plural': 'Парихмахеры',
            },
        ),
        migrations.AlterModelOptions(
            name='atmosfere',
            options={'verbose_name': 'Фоточки', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='titleAbout',
        ),
        migrations.RemoveField(
            model_name='services',
            name='titlePr',
        ),
        migrations.AlterField(
            model_name='atmosfere',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='atmosfere',
            name='podpis',
            field=models.CharField(max_length=250, verbose_name='Подпись к фото'),
        ),
    ]
