# Generated by Django 3.2.4 on 2021-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210624_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Как добраться',
                'verbose_name_plural': 'Как добраться',
            },
        ),
    ]
