# Generated by Django 3.1.7 on 2021-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210525_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title_for_section',
            name='titleAbout',
        ),
        migrations.RemoveField(
            model_name='title_for_section',
            name='titlePrice',
        ),
        migrations.AddField(
            model_name='title_for_section',
            name='titleAboutAndPrice',
            field=models.CharField(default='По порядку два заголовка', max_length=150, verbose_name='Заголовок'),
        ),
    ]
