# Generated by Django 3.1.7 on 2021-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210607_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmosfere',
            options={'verbose_name': 'Атмосфера', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='atmosfere',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
