# Generated by Django 3.1.7 on 2021-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210607_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosfere',
            name='podpis',
        ),
        migrations.AlterField(
            model_name='atmosfere',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
