# Generated by Django 3.1.7 on 2021-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210608_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosfere',
            name='podpis',
            field=models.CharField(default=123, max_length=250, verbose_name='Подпись к фото'),
            preserve_default=False,
        ),
    ]
