# Generated by Django 3.1.7 on 2021-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210608_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='map',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
