# Generated by Django 3.2.4 on 2021-06-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20210608_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiseServ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.services')),
            ],
        ),
    ]
