# Generated by Django 3.2.4 on 2021-06-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_chooseserv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooceServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Выбор услуг', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.services')),
            ],
        ),
        migrations.DeleteModel(
            name='ChooseServ',
        ),
    ]
