# Generated by Django 3.2.4 on 2021-06-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210618_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chooceserv',
            name='Выбор услуг',
        ),
        migrations.AddField(
            model_name='chooceserv',
            name='Выбор услуг',
            field=models.ManyToManyField(to='mainapp.Services'),
        ),
    ]
