# Generated by Django 3.2.4 on 2021-06-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210618_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairdressers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairdresser', models.CharField(max_length=200, verbose_name='Фамилия и имя')),
                ('master', models.CharField(max_length=40, verbose_name='Уровень мастерства')),
                ('aboutMaster', models.CharField(max_length=255, verbose_name='Немного о мастере')),
                ('avatar', models.ImageField(upload_to='img/', verbose_name='Добавить фото')),
            ],
            options={
                'verbose_name': 'Парихмахер',
                'verbose_name_plural': 'Парихмахеры',
            },
        ),
        migrations.DeleteModel(
            name='Title_for_section',
        ),
        migrations.RemoveField(
            model_name='chooceserv',
            name='Выбор услуг',
        ),
        migrations.AddField(
            model_name='chooceserv',
            name='Выбор услуг',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='mainapp.services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chooceserv',
            name='Выбор мастера',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='mainapp.hairdressers'),
            preserve_default=False,
        ),
    ]
